version: '3.8'
services:
  postgres:
    image: postgres:13.7-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=core
    volumes:
      - pgdata:/var/lib/postgresql/data
  test_database:
    image: postgres:13.7-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_core

volumes:
  pgdata:
