version: '3.8'
services:
  postgres:
    image: postgres:13.7-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=core
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nestjs_template_common

volumes:
  pgdata:

networks:
  nestjs_template_common:
    name: nestjs_template_common
